    version: 0.0
    os: linux
    files:
      - source: /
        destination: /var/www/html/
        overwrite: true
    hooks:
      AfterInstall:
        - location: scripts/unzip.sh
          timeout: 300
          runas: ec2-user
